export const questions = [
  {
    id: 1,
    question: "What is the distance of the trip you're planning?",
    A: "Up to 800 km on roads (ideal for traveling by car)",
    B: "More than 800 km or to another region/country (ideal for flying)",
    C: "Trips involving islands, coasts or rivers (good for boats)",
    D: "Medium to long distances between cities with rail service (good for trains)",
  },
  {
    id: 2,
    question: "What is your available budget for transportation?",
    A: "Moderate — fuel, tolls and car expenses are okay",
    B: "High — I can afford air tickets if needed",
    C: "Varies — boat tickets can be cheap or moderate",
    D: "Low to moderate — trains tend to be cost-effective",
  },
  {
    id: 3,
    question: "How much time can you spend traveling?",
    A: "A few hours, I don’t mind driving",
    B: "Very little — I need to arrive as fast as possible",
    C: "I can spend many hours enjoying a slow scenic route by water",
    D: "I can spend the day traveling comfortably by train",
  },
  {
    id: 4,
    question: "What type of experience are you looking for?",
    A: "Flexibility and comfort, stopping whenever I want (car)",
    B: "Speed and practicality with structured airports (airplane)",
    C: "Calm, scenic, relaxing water travel (boat)",
    D: "Comfortable and stable long-distance ride (train)",
  },
  {
    id: 5,
    question: "Do you feel comfortable traveling long distances?",
    A: "Yes, driving long hours is fine",
    B: "Yes, long flights are okay",
    C: "Yes, long boat trips are relaxing",
    D: "Yes, long train journeys feel comfortable",
  },
  {
    id: 6,
    question: "Do you have any fear of specific transport types?",
    A: "No fear — cars feel safest for me",
    B: "I’m afraid of flying",
    C: "I’m afraid of boats / sea",
    D: "I’m afraid of neither; rails feel safest",
  },
  {
    id: 7,
    question: "How much luggage will you carry?",
    A: "A lot — car space is ideal",
    B: "One or two suitcases (flight OK)",
    C: "Light to moderate luggage (boat cabins/bags)",
    D: "A backpack or suitcase that fits easily in trains",
  },
  {
    id: 8,
    question: "Will you travel alone or with more people?",
    A: "With family or small groups in one car",
    B: "Any group size — flights scale well",
    C: "Small group traveling together by boat",
    D: "Alone or with a few people on the same route",
  },
  {
    id: 9,
    question: "What type of terrain will you face?",
    A: "Roads, highways, mixed terrain (car)",
    B: "Terrain doesn’t matter — flying skips it",
    C: "Coastal, rivers or island access (boat)",
    D: "Cities connected by rail lines (train)",
  },
  {
    id: 10,
    question: "What weather conditions do you expect?",
    A: "Mixed weather but safe inside a car",
    B: "Weather may affect flights, but speed is key",
    C: "Calm or moderate weather at sea",
    D: "Cold or rainy weather — trains handle it well",
  },
  {
    id: 11,
    question: "What is more important to you?",
    A: "Flexibility and independence",
    B: "Fastest transportation possible",
    C: "Relaxation and scenic water travel",
    D: "Comfort and stable long-distance travel",
  },
  {
    id: 12,
    question: "Do you want to enjoy the landscape along the way?",
    A: "Yes, I enjoy driving scenic routes",
    B: "Not really, I just want to arrive quickly",
    C: "Yes, I love ocean/river views",
    D: "Yes, trains offer great landscapes",
  },
  {
    id: 13,
    question: "Do you prefer to control the vehicle or be guided?",
    A: "I prefer to drive myself (car)",
    B: "I prefer pilots to take control (plane)",
    C: "I prefer guided navigation on water (boat)",
    D: "I prefer guided rail travel (train)",
  },
  {
    id: 14,
    question: "How eco-friendly do you want your trip to be?",
    A: "Medium — depends on the car, but flexible",
    B: "Low priority — planes are not very eco-friendly",
    C: "High — boats can be efficient depending on the route",
    D: "Very high — trains are one of the greenest options",
  },
  {
    id: 15,
    question: "How easy is it to access transport options where you live?",
    A: "Easy road access and parking (car)",
    B: "Airport relatively close (plane)",
    C: "Port or water transport access nearby (boat)",
    D: "Train/bus station close by (train)",
  },
];
